source 'https://rubygems.org'

# Feel free to change this if you have a different version on your system.
ruby '2.1.4'

# Standard Rails gems
gem 'rails', '4.2.1'
gem 'sass-rails'
gem 'uglifier'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder'
gem 'bcrypt'
gem 'sqlite3'
gem 'devise'
gem 'figaro'

# Necessary for Windows (won't install on *nix systems)
gem 'tzinfo-data', platforms: [:mingw, :mswin]

gem 'kaminari'
gem 'font-awesome-sass'
gem 'bootstrap-sass'

group :development, :test do
  gem 'byebug'
  gem 'web-console'
  gem 'rspec-rails'
  gem 'pry'
  gem 'spring'
end
